### ISSUE TITLE
Stream not playing - "stream is no longer live"

### ISSUE THREAD

**Issue by Porkepix** [Perflyst/Twire#6] opened 2019-04-04 22:22 UTC
Any stream I tried to play from Twire is failing to play, displaying "Stream is no longer live" message, while this isn't true and can be played alsewhere.

Here are some `adb` logs if it can help, cleaned out for some parts:

```
04-04 23:28:11.522 30177 30177 I Timeline: Timeline: Activity_launch_request id:com.perflyst.twire time:731112887
04-04 23:28:11.523   927  3300 I ActivityManager: START u0 {cmp=com.perflyst.twire/.activities.stream.LiveStreamActivity (has extras)} from uid 10441 on display 0
04-04 23:28:11.592 30177 30177 D Settings: Saving Current Progress: 0
04-04 23:28:11.858 30177 30217 D ChatManager: Trying to start chat #channel for user porkepix
04-04 23:28:11.860 30177 30177 D LiveStreamActivity: Current orientation: 1
04-04 23:28:11.860 30177 30177 D StreamFragment: Showing navigation
04-04 23:28:11.916 30177 30177 D StreamFragment: WindowFocusChanged to true - isLandscape false
04-04 23:28:11.916 30177 30177 D StreamFragment: Showing navigation
04-04 23:28:11.919   927   987 I ActivityManager: Displayed com.perflyst.twire/.activities.stream.LiveStreamActivity: +376ms
04-04 23:28:11.919   927   987 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{8d80429 u0 com.perflyst.twire/.activities.stream.LiveStreamActivity t551} time:731113284
04-04 23:28:11.933 30177 30284 D ACCESS_TOKEN_STRING: {"adblock":false,"authorization":{"forbidden":false,"reason":""},"blackout_enabled":false,"channel":"channel","channel_id":71852533,"chansub":{"restricted_bitrates":["archives"],"view_until":1924905600},"ci_gb":false,"geoblock_reason":"","device_id":null,"expires":1554414390,"game":"League of Legends","hide_ads":false,"https_required":false,"mature":false,"partner":false,"platform":null,"player_type":null,"private":{"allowed_to_view":true},"privileged":false,"server_ads":true,"show_ads":true,"subscriber":false,"turbo":false,"user_id":null,"user_ip":"","version":2}
04-04 23:28:11.933 30177 30284 D GetLiveStreamURL: HSL Playlist URL: http://usher.twitch.tv/api/channel/hls/channel.m3u8?player=twitchweb&&token={"adblock":false,"authorization":{"forbidden":false,"reason":""},"blackout_enabled":false,"channel":"channel","channel_id":71852533,"chansub":{"restricted_bitrates":["archives"],"view_until":1924905600},"ci_gb":false,"geoblock_reason":"","device_id":null,"expires":1554414390,"","hide_ads":false,"https_required":false,"mature":false,"partner":false,"platform":null,"player_type":null,"private":{"allowed_to_view":true},"privileged":false,"server_ads":true,"show_ads":true,"subscriber":false,"turbo":false,"user_id":null,"user_ip":"","version":2}&sig=&allow_audio_only=true&allow_source=true&type=any&p=1
04-04 23:28:11.945 30177 30283 V URL TO JSON STRING: https://api.twitch.tv/api/channels/channel/panels did not successfully get read
04-04 23:28:11.945 30177 30283 V URL TO JSON STRING: Result of reading - []
04-04 23:28:11.962 30177 30177 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@71ee271 time:731113328
04-04 23:28:12.086 30177 30177 D StreamFragment: Fetching viewers
04-04 23:28:12.244 30177 30177 D ViewRootImpl: changeCanvasOpacity: opaque=true
04-04 23:28:12.443   927  3826 I MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@7b54914 req=1flags=0x0
04-04 23:28:12.445 30177 30177 E ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-04 23:28:12.445 30177 30177 E MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-04 23:28:12.445 30177 30177 E ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-04 23:28:12.445 30177 30177 E MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-04 23:28:12.446 30177 30177 W MediaPlayer: Couldn't open file on client side, trying server side
04-04 23:28:12.448 11901 30772 D NuPlayer: onSetVideoSurface(0x9e165f00, no video decoder)
04-04 23:28:12.448 11901 12298 D NuPlayerDriver: reset(0xab219840)
04-04 23:28:12.448 11901 12298 D NuPlayerDriver: notifyListener_l(0xab219840), (1, 0, 0)
04-04 23:28:12.449 11901 12298 D NuPlayerDriver: notifyListener_l(0xab219840), (8, 0, 0)
04-04 23:28:12.449 11901 30772 W AMessage: failed to post message as target looper for handler 0 is gone.
04-04 23:28:12.449 11901 30773 I LiveSession: onConnect http://<suppressed>
04-04 23:28:12.451 11901 30772 D NuPlayerDriver: notifyResetComplete(0xab219840)
04-04 23:28:12.451 11901 11901 D NuPlayerDriver: reset(0xab219840)
04-04 23:28:12.452   927  3809 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from android.media.AudioManager@7b54914
04-04 23:28:12.452   927  3320 I MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@7b54914 req=1flags=0x0
04-04 23:28:12.453 30177 30177 E ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-04 23:28:12.453 30177 30177 E MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-04 23:28:12.453 30177 30177 E ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-04 23:28:12.453 30177 30177 E MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-04 23:28:12.454 30177 30177 W MediaPlayer: Couldn't open file on client side, trying server side
04-04 23:28:12.455 11901 30775 D NuPlayer: onSetVideoSurface(0xa68dd000, no video decoder)
04-04 23:28:12.456 11901 30776 I LiveSession: onConnect http://<suppressed>
04-04 23:28:12.457 30177 30177 D StreamFragment: Starting Stream With a quality on auto for channel
04-04 23:28:12.458 30177 30177 D StreamFragment: URLS: [auto, medium, audio_only, low, chunked, high]
04-04 23:28:12.460 30177 30188 D MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= SonyD5803 Build/23.5.A.1.291 stagefright/1.2 (Linux;Android 6.0.1)
04-04 23:28:12.460 30177 30188 D MediaHTTPConnection: filterOutInternalHeaders: key=x-wap-profile, val= http://uaprof.sonymobile.com/D5803R2331.xml
04-04 23:28:12.461 30177 30189 D MediaHTTPConnection: proxy null port 0
04-04 23:28:12.464 30177 30177 D ChatFragment: Bttv Emotes loaded: 102
04-04 23:28:12.751 30177 30678 D MediaHTTPConnection: proxy null port 0
04-04 23:28:13.032 30177 30217 D ChatManager: <:tmi.twitch.tv 001 porkepix :Welcome, GLHF!
04-04 23:28:13.032 30177 30217 D ChatManager: <:tmi.twitch.tv 002 porkepix :Your host is tmi.twitch.tv
04-04 23:28:13.032 30177 30217 D ChatManager: <:tmi.twitch.tv 003 porkepix :This server is rather new
04-04 23:28:13.032 30177 30217 D ChatManager: <:tmi.twitch.tv 004 porkepix :-
04-04 23:28:13.033 30177 30217 D ChatManager: Connected >> porkepix ~ irc.twitch.tv
04-04 23:28:13.035 30177 30177 D ChatFragment: Chat connected
04-04 23:28:13.041 30177 30217 D ChatManager: <:tmi.twitch.tv 375 porkepix :-
04-04 23:28:13.041 30177 30217 D ChatManager: <:tmi.twitch.tv 372 porkepix :You are in a maze of twisty passages, all alike.
04-04 23:28:13.041 30177 30217 D ChatManager: <:tmi.twitch.tv 376 porkepix :>
04-04 23:28:13.078 11901 30776 E LiveSession: unable to fetch master playlist http://<suppressed>.
04-04 23:28:13.078 11901 30775 D NuPlayerDriver: notifyListener_l(0xac877780), (100, 1, -1004)
04-04 23:28:13.079 30177 30188 E MediaPlayer: error (1, -1004)
04-04 23:28:13.087 30177 30177 E MediaPlayer: Error (1,-1004)
04-04 23:28:13.087 30177 30177 D VideoView: Error: 1,-1004
04-04 23:28:13.087 30177 30177 E StreamFragment: Something went wrong playing the stream for channel - What: 1 - Extra: -1004
04-04 23:28:13.216 30177 30217 D ChatManager: <:tmi.twitch.tv CAP * ACK :twitch.tv/tags twitch.tv/commands
04-04 23:28:13.410 30177 30217 D ChatManager: <:porkepix!porkepix@porkepix.tmi.twitch.tv JOIN #channel
04-04 23:28:13.414 30177 30217 D ChatManager: <:porkepix.tmi.twitch.tv 353 porkepix = #channel :porkepix
04-04 23:28:13.414 30177 30217 D ChatManager: <:porkepix.tmi.twitch.tv 366 porkepix #channel :End of /NAMES list
04-04 23:28:13.415 30177 30217 D ChatManager: Failed to find roomstate pattern in: 
04-04 23:28:13.415 30177 30217 D ChatManager: @emote-only=0;followers-only=1;r9k=0;rituals=1;room-id=;slow=0;subs-only=0 :tmi.twitch.tv ROOMSTATE #channel
04-04 23:28:13.869 30177 30177 D ViewRootImpl: changeCanvasOpacity: opaque=false
```

**Comment by Perflyst** [comment] 2019-04-06 08:20
I cannot reproduce this. How do you start watching? Playlist? Via user profile?

**Comment by Porkepix** [comment] 2019-04-06 09:34
I get this result whatever the way I goes on a stream (top streams, features streams, followed streams and so on). I have the static image of the stream but bottom shows "Stream is no longer live" message everytime and I can't play it within the app.

Even more strange: I can use the three dots and ask to play it in an external player, and in that case it works. So it's only stream within the app itself which is broken (and status check resulting in the display of this message).

No useful information can be obtained from the `adb logcat\ above?

**Comment by omarelhajj97** [comment] 2019-04-08 06:36
Same exact issue here. Android 6.0.1.

**Comment by Perflyst** [comment] 2019-04-09 17:11
Would it be possible that you test with the "original" version before I forked it? You can find it here: https://play.google.com/store/apps/details?id=net.nrask.notifyme

If this also appears on this app I would suggest to submit this bug to upstream, otherwise I will take a further look.

**Comment by Porkepix** [comment] 2019-04-09 17:20
> Would it be possible that you test with the "original" version before I forked it? You can find it here: https://play.google.com/store/apps/details?id=net.nrask.notifyme
> 
> If this also appears on this app I would suggest to submit this bug to upstream, otherwise I will take a further look.

Okay so, although it was not cool to have to install some crap with trackers (https://reports.exodus-privacy.eu.org/en/reports/68925/), I used Blokada to clean a bit what it could try to report, and result is that it works, sadly (stream plays correctly, it's just a bit slow to start).

I thought you didn't do many notifications as of now and just cleaned the Google crap from the application? (Also noticed an orange popup inviting to discover streams, not in Twire iirc)?

**Comment by Porkepix** [comment] 2019-04-09 17:23
Eh, actually I saw that in the what's new part on the play store it talks about
```
What's New
Fixed issue where stream would not play on Android 6.0
Fixed issue where emotes and stream thumbnails would not load on some devices.
```

But last update is from september 2018.

Is your fork older than that? Are you not up to date with upstream?
It looks related to last commit, https://github.com/SebastianRask/Pocket-Plays-for-Twitch/commit/43790d4d0465e4d8933a5250af9bef2d00033da0

**Comment by Perflyst** [comment] 2019-04-09 17:31
I didn't do any changes to the stream handling. It can be some library changes because I updated them

**Comment by Porkepix** [comment] 2019-04-09 17:33
Yeah I could actually have checked the commit logs.
No idea then about why in one case it can play and not in another one.

**Comment by bailli** [comment] 2019-04-10 14:48
I can confirm this bug, too. Running Twire on Android 4.4.4 - security-wise this is mostly up-to-date.

Opening the stream in VLC works for me, too. When I tried to open streams without logging into my twitch account, I did not get an error message, the app only kind of froze.

**Comment by bioblatt** [comment] 2019-04-14 21:39
I have the same problem. 

Android 8.1.0

**Comment by zJoul** [comment] 2019-04-20 09:12
I have the same problem, running Android 6.0

But I think I spotted a scheme : whenever I'm trying to play a stream, if the game have a space in it's name, it fail.

Exemple right now, with random games :
* Baba is you, world of warcraft, gta : fail
* hearstone, fortnite, forager : ok

Althought I should make another issue, the chat never worked

**Comment by Porkepix** [comment] 2019-04-20 09:17
Oh, very nice spot.
So, same here, stream of a game without space in the name did run.

Chat never got any issue here though, I have it.

**Comment by Porkepix** [comment] 2019-04-20 09:28
"Good news" @Perflyst , following @zJoul comment I tried the two types of games in the upstream application: same issue.
I got unlucky with the random pick of my previous try.

**Comment by Perflyst** [comment] 2019-04-20 10:22
Thanks for the informations

**Comment by Porkepix** [comment] 2019-04-21 00:20
I referenced it on upstream's issue that already existed. No idea if this will still be maintained though.
If with @zJoul's information you can now reproduce it, maybe is it possible to remove the `not reproducible` tag? :)

**Comment by Disqu3-mirOir-qt** [comment] 2019-04-24 08:23
I have the same problem on some live shows

**Comment by minami-o** [comment] 2019-05-31 21:29
Same problem here, only on some live show...

**Comment by Littlemac123** [comment] 2019-12-03 19:28
![Screenshot_20191203-142147](https://user-images.githubusercontent.com/39867553/70082613-b1fb3f00-1602-11ea-81f8-84f5ad4b7fa9.png)
I get the bug joining any stream on the site that is clearly live, and I don't even hear any audio or anything but I am able to chat just fine. I'm on Android 7.1.1 Moto g4 not plus
using VLC threw the external player does work fine but I don't like using VLC witch twitch because the delay is really bad

**Comment by samfundev** [comment] 2020-07-11 18:33
I'm going to close this issue. Streams with ampersands and spaces are working so I think the original issue is solved. If you've tried changing qualities and are sure the stream is live, open a separate issue ideally with a log.

**Closed by samfundev** 2020-07-11 18:33 UTC
Labels: bug
