### ISSUE TITLE
bug Stream no longer live

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [Perflyst/Twire#28] opened 2019-06-27 14:18 UTC
some streams don't work here is the network request in order to see more clearly:

http://usher.twitch.tv/api/channel/hls/manaprod.m3u8?player=twitchweb&&token={%22adblock%22:false,%22authorization%22:{%22forbidden%22:false,%22reason%22:%22%22},%22blackout_enabled%22:false,%22channel%22:%22manaprod%22,%22channel_id%22:58737711,%22chansub%22:{%22restricted_bitrates%22:[],%22view_until%22:1924905600},%22ci_gb%22:false,%22geoblock_reason%22:%22%22,%22device_id%22:null,%22expires%22:1561646124,%22game%22:%22Might%20u0026%20Magic:%20Elemental%20Guardians%22,%22hide_ads%22:false,%22https_required%22:false,%22mature%22:false,%22partner%22:false,%22platform%22:null,%22player_type%22:null,%22private%22:{%22allowed_to_view%22:true},%22privileged%22:false,%22server_ads%22:true,%22show_ads%22:true,%22subscriber%22:false,%22turbo%22:false,%22user_id%22:null,%22user_ip%22:%22109.14.159.137%22,%22version%22:2}&sig=924dde3686ada62a4f5ec1d0f7da28a800689a52&allow_audio_only=true&allow_source=true&type=any&p=1

here is the url of a stream that works:

http://video-weaver.cdg02.hls.ttvnw.net/v1/playlist/CssDvwW_iQ7lJNncXbluXd_RgFKe191DtDZQ7rZYcnK2NBL9ypMHpEiWzyeZB4hc4ewnx2RVuww7sGZ79JP756RljA6wSi4svPOiDZibE4P9KnPYirBVrnWUS7HAvv9RATfTRMQKVeEqHKv_-MYdqzQCMKOYAUfTlDjmvbvRMEArcQGY6LIPoSAe47kDNdsgTx29FhUNOgwAsZX-YyYRO5a017rZeqVoWDmwbg8wzmzRB0wbIbkNioWNM3cIjTS9ELUTa1-rLceYtz3u9JMbdhUH9mAL6mjualgsjN0i3TRaiD4ggRVeUl85GXlzAk-kYW1w5M_QnUJln-BRIk08ng5sXBn6Rk9liwjXNjWk-WARHCHypP_5BPVauKF_JBQLZFrGZC7vANHHc4O6FKOr1WGGFa3vya0bP6CMYpxLEN7pTF428uF6ddGLcuApirsEEEHmqu8cN-FpcOAtqjMDK2iO5JuTGe6SD7fLY83fnxz5eo3E0BjPm5-QPH4-PgKjF6tOtiDTkk10LsEDYlXZGV9AxJhY3RF34o365xrK4FDJlM_ExyeTfrDvPteT3M6Tt4FhdbfZ_JlfZjniK6wQYhXkssmbNtr0UV8RBaRTEhA3AjN_cqCunsdc7AXCDElSGgy7AiE9cu5QBmucmSs.m3u8

**Comment by GR412** [comment] 2019-08-13 18:06
I get this too, I can hear the audio of a stream fine, but the video is a black screen. When I try to load chat it just says the stream is no longer live. Although using an external player (VLC) worked for video and audio on my android phone.

**Comment by Perflyst** [comment] 2019-09-15 09:14
Duplicate of #6

**Closed by Perflyst** 2019-09-15 09:14 UTC
